### ISSUE TITLE
Integration tests with test data and lua scripts

### ISSUE THREAD

**Issue by oetterer** [SemanticMediaWiki/SemanticScribunto#27]
It would be good to have online test data to run some more plausible tests with travis for `mw.smw.ask` and `mw.smw.getQueryResult`. Unfortunately, my knowledge and experience is verly limited in that regard, as I am just beginning to work with unittests (who would have guessed ;) ).

My approach would be to have `install-semantic-scribunto.sh` import some xml files and run the maintenance scripts once, but I'm guessing there is a better way.

**Comment by mwjames** [comment]
> My approach would be to have install-semantic-scribunto.sh import some xml files and run the maintenance scripts once, but I'm guessing there is a better way.

You could to that but that is very inflexible and your are not able to run those tests locally making if difficult to debug issues in case of an error.

I'm more in favour of what we have done in SMW [0, 1] because the objective for an integration test is to establish and verify the behaviour as a whole which is a bit different from writing unit tests.

Integration tests don't replace the unit tests, they complement them to verify that an expected outcome does actually occur (on the contrary, unit tests are like an isolated island with no connection to a mainland).

You could take the `PHPUnit_Framework_TestCase` and the `MwDBaseUnitTestCase` and make it work which was done son in the past but it became clear after a certain amount of tests that this approach (where you need to define setup/tearDown each entity) to define integration scenarios doesn't scale very well.

The system is fairly simple, we use the `JSON` format to define a test case with pages and content we'd like to use together with the assertion that will run for each file found in the `TestCases` location. The main entry point will be the `SemanticScribuntoJsonTestCaseScriptRunnerTest` [2] which extends the `JsonTestCaseScriptRunner`  and is responsible for establishing the DB connection, create and tear down pages, and provide utility functions to make the whole exercise a no-frills activity.

The higher the amount of collected integration tests, the more confidence can be declared that undetected regressions aren't introduced (which doesn't say much since you cannot be sure that the current behavior isn't free from a divergent behavior).

As for the process, normally it would be:

- If you have a bug or regression then try to make a conjecture or hypothesis about the cause
- Find a minimal test case (using wiki text at this point makes life much more easier)
- Write a `JSON` test and have it fail
- Apply the fix
- Run the test again and then run all other integration tests to ensure nothing else fell through the cracks by accidentally introducing another regression not directly related to what you have fixed

PS: Of course, those integration tests require more runtime as they emulate the input of a human (running through the normal page editing process, no short cut here) on top of the of the assertions. In case of SMW, half of test suite runtime is dedicated to the integration tests with only the 5th of the total amount of tests being integration tests.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#write-integration-tests-using-json-script
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/JSONScript
[2] https://github.com/SemanticMediaWiki/SemanticScribunto/blob/master/tests/phpunit/Integration/JSONScript/SemanticScribuntoJsonTestCaseScriptRunnerTest.php

**Comment by oetterer** [comment]
I'm at a loss for words. This is amazing. Let me start with thanking you for providing the ground work for all of this. And more importantly: thank you very much for taking the time and explaingit all in so much detail. That really helps a lot - not only for this project. :) I'm constantly learning new things working on SSC.

As a start I tried a take on the open issue of result order. I also added a few base tests for getQueryResult. Next week I'll continue with info, set and subobject. If you have more suggestions for tests, give them to me. I'll try to take care.

Looking forward to a first relase in 2017. :+1:
